FROM python:3.8-buster

COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

COPY . /dogbot
RUN cd /dogbot && python3 -m pip install .

WORKDIR /dogbot
